model:
  encoder:
    joint_processing:
      layer_sizes:
      - 256
      obs_key: goalwards_xy
    vision_preprocessing:
      dense:
        layer_sizes:
        - 256
        obs_key: null
      filter_sizes:
      - 16
      - 32
      - 32
      obs_key: privileged_terrain_map
  encoder_supersteps: 16
  latent_encoding_size: 128
  model_class: TeacherStudentRecurrent
  policy:
    layer_sizes:
    - 256
    - 128
    - 128
    obs_key: proprioceptive_history
  student:
    convolutional:
      dense:
        layer_sizes:
        - 128
        - 64
        obs_key: null
      filter_sizes:
      - 16
      - 32
      - 32
      obs_key: pixels/ego_frontal/rgb_adjusted
    proprioceptive_preprocessing:
      layer_sizes:
      - 128
      - 64
      obs_key: proprioceptive
    recurrent:
      dense:
        layer_sizes:
        - 128
        obs_key: null
      recurrent_size: 128
  student_encoder_supersteps: 4
  student_recurrent_backpropagation_steps: 64
  value:
    layer_sizes:
    - 256
    - 256
    - 256
    obs_key: proprioceptive_history
training:
  action_repeat: 1
  augment_pixels: false
  batch_size: 16
  deterministic_eval: false
  episode_length: 50
  log_training_metrics: false
  normalize_observations: true
  num_envs: 256
  num_eval_envs: 256
  num_evals: 10
  num_minibatches: 16
  num_resets_per_eval: 0
  num_timesteps: 10000000
  num_updates_per_batch: 2
  optimizer:
    learning_rate: 0.0004
    max_grad_norm: 1.0
    student_learning_rate: 0.001
  rl_hyperparams:
    clipping_epsilon: 0.3
    discounting: 0.97
    entropy_cost: 0.01
    gae_lambda: 0.95
    normalize_advantage: true
    reward_scaling: 1
  seed: 0
  training_class: PPO_RecurrentStudent
  training_metrics_steps: null
  unroll_length: 4
  use_vision: true
  vision_frame_height: 64
  vision_frame_width: 64
