model:
  encoder:
    dense:
      layer_sizes:
      - 256
    filter_sizes:
    - 16
    - 32
    - 32
  encoder_obs_key: privileged_terrain_map
  encoder_supersteps: 16
  latent_encoding_size: 256
  model_class: TeacherStudentRecurrent
  policy:
    layer_sizes:
    - 256
    - 128
  policy_obs_key: proprioceptive
  student:
    convolutional:
      dense:
        layer_sizes:
        - 128
        - 64
      filter_sizes:
      - 16
      - 32
      - 32
    proprioceptive_preprocessing:
      layer_sizes:
      - 128
      - 64
    recurrent:
      dense:
        layer_sizes:
        - 128
      recurrent_size: 128
  student_encoder_supersteps: 4
  student_obs_key: pixels/frontal_ego/rgb_adjusted
  student_proprio_obs_key: proprioceptive
  student_recurrent_backpropagation_steps: 64
  value:
    layer_sizes:
    - 256
    - 256
  value_obs_key: proprioceptive
training:
  action_repeat: 1
  augment_pixels: false
  batch_size: 4
  deterministic_eval: false
  episode_length: 50
  log_training_metrics: false
  normalize_observations: true
  num_envs: 4
  num_eval_envs: 4
  num_evals: 5
  num_minibatches: 4
  num_resets_per_eval: 0
  num_timesteps: 100000
  num_updates_per_batch: 2
  optimizer:
    learning_rate: 0.0004
    max_grad_norm: 1.0
    student_learning_rate: 0.001
  rl_hyperparams:
    clipping_epsilon: 0.3
    discounting: 0.97
    entropy_cost: 0.01
    gae_lambda: 0.95
    normalize_advantage: true
    reward_scaling: 1
  seed: 0
  training_class: PPO_RecurrentStudent
  training_metrics_steps: null
  unroll_length: 4
  use_vision: true
